### ISSUE TITLE
Varningsmedelande vid lyckad decoding

### ISSUE THREAD

**Issue by Cstaf** [cancercentrum/decoder#48]
Om du minns när vi arbetade med valideringen fick vi ett konstigt varningsmedelande när vi använde denna funktion. Här är ett exempel:

"2: c(138201L, 138201L, 138206L, 138208L, 138208L, 138301L, 138301L, 138311L, 138320L, 138404L, 138404L, 138405L, 138407L, 138408L, 138408L, 138414L, 140102L, 140103L, 140104L, 140201L, 140203L, 144001L, 144003L, 144101L, 144103L, 144302L, 144502L, 144603L, 146001L, 146006L, 146006L, 146101L, 146304L, 146307L, 147118L, 148005L, 148008L, 148008L, 148009L, 148011L, 148012L, 148013L, 148013L, 148013L, 148016L, 148016L, 148017L, 148017L, 148017L, 148017L, 148020L, 148020L, 148020L, 148021L, 148022L, 148022L, 148022L, 148022L, 148022L, 148024L, 148031L, 148032L, 148032L, 148034L, 148034L, 148034L, 148034L, 148034L, 148034L, 148034L, 148034L, 148034L, 148036L, 148041L, 148101L, 148101L, 148101L, 148102L, 148103L, 148103L, 148103L, 148201L, 148201L, 148208L, 148501L, 148512L, 148601L, 148701L, 148701L, 148801L, 148801L, 148807L, 148901L, 148901L, 149002L, 149002L, 149002L, 149011L, 149016L, 149101L, 149101L, 149128L, 149201L, 149301L, 149431L, 149601L, 149601L, 149701L, 149701L, 149701L, 149701L, [... truncated] "

Vore bra att undersöka detta, undersökte decoderfunktionen och hitta ingen orsak för detta varningsmedelande.

**Comment by eribul** [comment]
Jag är inte helt säker men tror att jag fixat detta i senaste versionen som jag hade på min dator. Av ngn anledning hade jag dock missat att uppdatera paketet på GitHub men förhoppningsvis ska det alltså funka nu!

**Comment by eribul** [comment]
Tydligen funkar det fortfarande inte riktigt! Det är dock inte msg-strängen i `format_as_key` som ställer till det utan att funktionen anropas från XXX med `name_x`som ett väldigt långt namn!

**Comment by eribul** [comment]
Det hela kommer sig av följande från `decoder.default`:
`name_x <- deparse(substitute(x))`

**Comment by eribul** [comment]
Byt ut denna rad till:
`deparse(substitute(x, parent.frame()))`

**Comment by eribul** [comment]
Nu är de långa varningarna borta! Å andra sidan blir det bet otydligare varifrån felet kommer. Så är fortf inte helt nöjd!

**Comment by eribul** [comment]
Tar tillbaka till så som det var innan. Allt funkar om man anropar `decode`-funktionen direkt men inte om man går via `dplyr::mutate`.

Misstänker att det kanske kan vara NSE som spökar?

**Comment by eribul** [comment]
Kan helt enkelt vara dplyr som implementeras så. Man gör lite speciella saker där för att använda C-kod etc och inte R. Tror det är därför!
